eureka:
    instance:
        client:
            serviceUrl:
                defaultZone: http://localhost:8761/
server:
    port: 8086
spring:
    application:
        name: Email-Service
    mail:
        host: smtp.gmail.com
        password: forgrhbgftvedmvu
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
        username: insys2stunteam@gmail.com
urlApp: http://localhost:5173/verify
