spring:
  application:
    name: RuleService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.insycs.fr/realms/KeyClock-InsyProcess
          jwk-set-uri: https://keycloak.insycs.fr/realms/KeyClock-InsyProcess/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MoteurDeRegleV7
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 7081
