eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/
server:
  port: 8082

spring:
  application:
    name: security-service
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.insycs.fr/realms/KeyClock-InsyProcess
          jwk-set-uri: https://keycloak.insycs.fr/realms/KeyClock-InsyProcess/protocol/openid-connect/certs
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ':::::::::::: Hikari DS Spades_1-MS POOL ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/securitykeycloakV1
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

email:
  url: http://localhost:9090/api/mail

keycloak:
  server-url: "https://keycloak.insycs.fr/"
  realm: "KeyClock-InsyProcess"
  client-id: "KeyClock-InsyProcess-Client"
  client-secret: "IiOfARfODI8X6y2ChpC0Zk3Gu0f5CNMm"
  admin-username: "insy2s"
  admin-password: "insy2s"
