eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/


server:

  port: 7080

spring:
  application:
    name: WorkflowService
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://keycloak.fethi.synology.me/auth/realms/KeyClock-INSY2S-PROCESS
            jwk-set-uri: https://keycloak.fethi.synology.me/auth/realms/KeyClock-INSY2S-PROCESS/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/WorkflowV1
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      # TODO: needs to disable ddl-auto and use a database migration tool like liquibase
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            format_sql: true
    open-in-view: false