eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/


server:

  port: 7080

spring:
  application:
    name: WorkflowService
  datasource:
    url: jdbc:postgresql://localhost:5432/insy2s
    username: postgres
    password: proxym2023
  jpa:
    show-sql: true
    hibernate:
      # TODO: needs to disable ddl-auto and use a database migration tool like liquibase
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            format_sql: true
    open-in-view: false